### PR TITLE
Update ttl-options.md

### PR DESCRIPTION
**Pull request by qingyan01**
增加修改边ttl的示例

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by wey-gu** [comment]
@qingyan01 welcome to the community! Would you mind signing the CLA? By juust clicking the following badge and sign the agreement. So we could move forward with this contribution.

Thanks!

>  [CLA assistant check](https://cla-assistant.io/vesoft-inc/nebula-docs?pullRequest=2520)

**Comment by wey-gu** [comment]
Also, would you mind updating the equivalent change to the en docs on the same PR branch for file: `docs-2.0-en/3.ngql-guide/8.clauses-and-options/ttl-options.md`?

Thanks!

**Comment by QingZ11** [comment]
@qingyan01 谢谢你帮忙完善文档。你可以点击黄色 CLA 图标签订下协议，协议的大概内容是你贡献的内容是为你所有，但是可以被 nebula 所用。

你的文档示例是给 ttl 增加一个边修改的变更，为了让语句更加严谨，你可以在插入边之前，插入 100 的点，参考上面 101 点插入的方式。

Thank you for your contribution. You can click on the yellow CLA badge to sign the agreement. The agreement states that the content you contribute remains yours but can be used by nebula.

Regarding your documentation example, you are making a modification to add an edge with a TTL. To make the statement more precise, you can insert `100` vertex before inserting the edge, following the same approach as the insertion of vertex `101` mentioned above.

**Comment by qingyan01** [comment]
已经同意了协议，docs-2.0-en/3.ngql-guide/8.clauses-and-options/ttl-options.md这个也添加了相同的示例了

**Review by cooper-lzy — APPROVED** [review]

**Review by cooper-lzy — APPROVED** [review]

**Pull request merged**
